# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    services:
      postgres:
        # Docker Hub image
        image: postgres
        restart: always
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: yarn install

    - name: Connect to PostgreSQL
      run: cd packages/game-data && yarn ts-node --transpileOnly setupDb.ts
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_DB: rhythm

    - run: cd packages/game-data && yarn build-schema && cd ../..
    - run: cd packages/frontend && yarn codegen && yarn tailwind:build && cd ../..
    - run: yarn lint:check
    - run: yarn check-ts
    - run: yarn test
    - run: yarn build # make sure prod build is working
